import React, { Component } from 'react';
import Sider from "./../Common/Sider/Sider";
import { postService } from "../../Services/postsService";
class Home extends Component {
    state = {};
    componentDidMount() {
        postService.getPosts().then(data => console.log(data));
    }
    render() {
        return <div className="pages__home">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo laoreet turpis et ultricies. In in risus sagittis, luctus nunc ac, congue metus. Aliquam odio leo, lacinia a lorem eget, imperdiet posuere dolor. Curabitur nec tempor metus. Quisque dapibus ultricies massa tristique porta. Sed id magna ante. Pellentesque sit amet velit ac metus placerat luctus. Morbi scelerisque lacus tortor. Pellentesque et nibh massa. Donec dignissim metus ac augue tincidunt, a rutrum augue posuere. Donec malesuada leo eros, nec lobortis neque eleifend eget. Donec pharetra mauris et purus euismod elementum. Maecenas volutpat consequat felis at hendrerit. Donec laoreet dapibus tellus at fringilla. Etiam ex neque, fermentum a leo id, laoreet auctor risus. Proin dictum finibus sapien egestas aliquet.

In eget accumsan dolor, eu rhoncus mi. In eget congue metus. Cras vehicula dolor justo, quis fringilla dolor tristique eu. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque at urna nec tortor suscipit tempor nec in justo. Proin lobortis tortor neque, eu molestie lorem faucibus ut. Nulla facilisi. Ut eu luctus libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent feugiat consequat nunc eu cursus. Etiam sit amet sem ligula. Nam at pellentesque eros. Nunc feugiat nisl eu purus ullamcorper ultricies. Nunc accumsan nisl a quam ultricies consectetur. Mauris quam est, suscipit vitae dui nec, auctor sodales lectus.

Ut maximus tempus mauris tincidunt vehicula. Vestibulum quis tortor quis elit congue lobortis nec eget sem. Quisque ornare arcu ante, quis efficitur magna maximus vel. Aenean magna quam, molestie eu interdum sed, laoreet non nisl. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent eu ante auctor, convallis nibh vel, convallis dui. Nam in lorem lacus. Integer condimentum arcu sit amet tincidunt varius. Suspendisse potenti. Morbi rutrum efficitur metus, a auctor neque tincidunt eget. Ut sit amet diam eu mi aliquam feugiat et sed urna.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam facilisis sollicitudin dictum. Aliquam ornare ipsum mauris, et faucibus mi cursus ac. Curabitur at vulputate ex. Vestibulum id lorem a turpis maximus imperdiet. Vestibulum convallis, ipsum in tempor dapibus, risus lacus interdum augue, eu laoreet odio elit eget nisi. Mauris ultrices risus tellus, non suscipit dui bibendum in. Quisque tempus risus id interdum scelerisque. Proin eu ullamcorper arcu. Nam nec ipsum sed nisi faucibus sagittis. Proin sed mattis sem.

Donec eleifend enim ut nulla pulvinar tristique. Vivamus a molestie risus, finibus pellentesque turpis. Donec iaculis nulla et ultricies scelerisque. Sed risus urna, efficitur ut placerat nec, rutrum imperdiet ex. Nam bibendum felis eu odio feugiat gravida. Donec id elit eu nulla feugiat molestie. Aliquam commodo tortor ac enim commodo lacinia. Fusce dui neque, facilisis sed diam quis, blandit tristique arcu. Quisque euismod commodo ex, et iaculis leo fermentum eu. Suspendisse potenti. Proin id efficitur purus. Nunc sed pulvinar augue. Integer nisi ligula, lobortis at elit et, aliquam viverra ante. Sed tempus rhoncus tellus, et congue turpis tempus ut.

Fusce luctus quis risus a laoreet. Donec sodales enim sit amet ante bibendum pulvinar. Pellentesque sed tincidunt lorem, eu vehicula lorem. Aliquam arcu magna, convallis id metus a, eleifend tincidunt ante. Nulla id lacinia est. Aliquam erat volutpat. Mauris posuere turpis nisi, at lobortis sem pulvinar vitae.

Sed ultrices congue mi vitae molestie. Vivamus condimentum massa a fringilla dapibus. Donec faucibus risus a leo pellentesque blandit. Phasellus maximus suscipit ipsum, ut scelerisque neque fermentum ut. Vivamus vulputate consectetur sem, et commodo nisi faucibus in. Vivamus convallis odio ut purus dignissim lobortis. Nunc blandit eget tellus ac egestas. Curabitur bibendum nunc id nunc tincidunt, sit amet ultricies odio pharetra. Aliquam in facilisis tellus. Ut sed tempus massa. Praesent quis quam felis. Fusce placerat, justo sit amet interdum varius, sem augue venenatis nunc, ut dapibus libero enim ut sapien. Integer vitae urna ac elit sodales vehicula. Integer sagittis, justo vitae porttitor consequat, massa lorem finibus ante, eu hendrerit velit diam non elit.

Duis euismod lacus sed pretium malesuada. Nulla lobortis ipsum magna, quis gravida magna iaculis quis. Fusce consequat nisi sapien, sit amet commodo quam semper ut. Sed faucibus erat quis sollicitudin tempus. Nullam nec leo ornare, pretium eros et, molestie odio. Ut dictum aliquam nibh at hendrerit. Cras cursus nisi eget elementum elementum. Nulla eu bibendum elit, nec iaculis sem. Nullam fringilla facilisis lacus eu feugiat. Duis auctor pretium enim, et sollicitudin est imperdiet id. Nunc a erat commodo, porttitor ex id, auctor velit. Suspendisse in egestas augue. Sed dictum consequat diam, a vehicula tortor cursus cursus. Donec molestie nunc sed felis convallis rhoncus. Proin et arcu arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Cras id libero non arcu mattis tempus. Integer mattis tristique magna vel consequat. Vivamus posuere enim eu purus vulputate, a gravida ipsum congue. Proin in mattis ex, sed placerat ante. Curabitur tempus ante eros, suscipit mattis nulla feugiat non. Praesent nibh dui, congue non scelerisque vel, convallis et ligula. Pellentesque sit amet commodo orci. Pellentesque vitae fermentum urna. Morbi iaculis nisi at enim dapibus, in posuere neque efficitur. Phasellus et metus ut mauris finibus condimentum eget id purus.

Fusce auctor mi fringilla lobortis rhoncus. Quisque non urna justo. Cras pretium massa quis massa feugiat venenatis. Donec non nunc mattis eros rhoncus lacinia id vel erat. Praesent rutrum quam odio, eu mollis nunc vulputate sed. Morbi felis quam, aliquam vel vulputate id, dictum porttitor ex. Aenean purus urna, auctor hendrerit sem sed, sodales aliquet magna. Fusce vestibulum turpis vel nisl mollis, a blandit mauris placerat. Nunc et elit dolor. Vestibulum nec tortor vel ligula cursus tristique in eu leo. Suspendisse id ligula ante.

Pellentesque sed erat enim. Nullam eu tristique nunc, cursus imperdiet velit. Proin nibh nulla, cursus eu orci vitae, vestibulum tempus justo. Pellentesque id orci non ligula dignissim efficitur. Fusce nec justo sollicitudin, pretium nulla ut, molestie neque. Sed ac massa laoreet, eleifend augue molestie, tincidunt est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam commodo nec orci ac porta. Donec ornare iaculis iaculis. Nullam in vehicula velit. Pellentesque scelerisque libero laoreet, congue eros sed, vehicula libero.

Integer ac ligula eget enim egestas ultrices at eget elit. Cras ante diam, tincidunt eget leo id, rhoncus posuere magna. Nunc porta dolor non pharetra maximus. Nullam sit amet tortor facilisis, interdum tortor eu, euismod mi. Integer imperdiet in nisi nec lobortis. Nulla facilisi. Cras porttitor elementum vehicula. Morbi facilisis dui ut nunc pretium, in tincidunt neque mollis. Mauris et magna felis. Donec ultricies felis in libero condimentum, eu euismod urna interdum.

Morbi maximus semper molestie. Etiam nisi est, sagittis a metus vitae, sollicitudin dapibus nisl. Curabitur euismod dapibus massa eu venenatis. Sed vitae elit id eros molestie sodales id vel sapien. Nam maximus rutrum purus, a sodales nisl iaculis at. Sed faucibus blandit massa in pulvinar. Vestibulum auctor malesuada tellus at feugiat. Vestibulum iaculis rutrum leo, ut porta nunc commodo quis. Proin dapibus suscipit dolor, ac mollis ipsum placerat ac. Nunc ultrices lorem ut quam gravida tincidunt. Vivamus sit amet tortor vel eros tempor tempus vitae sit amet sem. Fusce scelerisque dolor nec urna cursus, ac aliquam quam sagittis. Etiam auctor est tortor, at porttitor eros fringilla ac. Nullam mauris libero, venenatis vitae placerat in, fringilla vel ante. Donec pellentesque libero sit amet fermentum luctus.
        </div>;
    }
}

export default Home;